# fly.toml app configuration file generated for pairprogram-me on 2023-10-11T20:16:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pairprogram-me"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
